# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hostgroup',
            unique_together=set([('host_group_name', 'host_group_jd')]),
        ),
        migrations.AlterUniqueTogether(
            name='usergroup',
            unique_together=set([('user_group_name', 'user_group_jd')]),
        ),
        migrations.AlterUniqueTogether(
            name='userhostrelationship',
            unique_together=set([('user_group', 'host_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set([('user_role_name', 'user_role_jd')]),
        ),
    ]
