# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='host_ip',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
