# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_pass',
            field=models.CharField(max_length=96),
        ),
    ]
