# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfoAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_user', models.CharField(max_length=20)),
                ('host_pass', models.CharField(max_length=30)),
                ('host_port', models.SmallIntegerField()),
                ('app_user', models.CharField(max_length=20)),
                ('app_pass', models.CharField(max_length=30)),
                ('app_port', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'cmdb_host_auth',
            },
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='host_group',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostGroup'),
        ),
        migrations.AlterField(
            model_name='hostinfo',
            name='host_ip',
            field=models.UnsignedIntegerField(unique=True),
        ),
        migrations.AlterIndexTogether(
            name='hostinfo',
            index_together=set([]),
        ),
        migrations.AddField(
            model_name='hostinfoauth',
            name='host',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='cmdb.HostInfo'),
        ),
        migrations.RemoveField(
            model_name='hostinfo',
            name='app_pass',
        ),
        migrations.RemoveField(
            model_name='hostinfo',
            name='app_port',
        ),
        migrations.RemoveField(
            model_name='hostinfo',
            name='app_user',
        ),
    ]
