# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-20 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_idc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDC',
        ),
    ]
