# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-19 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20170519_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostinfoauth',
            name='host_pass',
        ),
        migrations.RemoveField(
            model_name='hostinfoauth',
            name='host_port',
        ),
        migrations.RemoveField(
            model_name='hostinfoauth',
            name='host_user',
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='host_pass',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='host_port',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='host_user',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
