# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionworkorderinfo',
            name='db_host',
            field=models.CharField(max_length=45),
        ),
    ]
