# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlBackupSourceInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('generator_room_name', models.CharField(max_length=30)),
                ('defaults_file', models.CharField(max_length=100)),
                ('r_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
