# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 08:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0002_mysqlbackupsourceinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysqlBackupSourceInfo',
        ),
    ]
