# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0004_workordertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordertask',
            name='host_ip',
            field=models.CharField(max_length=45),
        ),
    ]
