# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-25 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0005_auto_20170525_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionauditdetail',
            name='error_msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inceptionauditdetail',
            name='sql_content',
            field=models.TextField(),
        ),
    ]
