# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0009_delete_mysqlbackupsourceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysqlBackupSourceInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('generator_room_name', models.CharField(max_length=30)),
                ('ipaddr', models.IntegerField()),
                ('port', models.SmallIntegerField()),
                ('service_level', models.SmallIntegerField()),
                ('defaults_file', models.CharField(max_length=100)),
                ('back_time', models.TimeField()),
                ('transport_time', models.TimeField()),
                ('is_transport', models.SmallIntegerField()),
                ('back_pool_id', models.SmallIntegerField()),
                ('r_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dbms_mysql_backup_source_info',
            },
        ),
    ]
