# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0012_mysqlbackupsourceinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MysqlBackupSourceInfo',
        ),
    ]
