# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbms', '0014_auto_20170419_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupedBinlogInfo',
        ),
        migrations.DeleteModel(
            name='BackupedInfo',
        ),
        migrations.DeleteModel(
            name='BackupPoolInfo',
        ),
        migrations.DeleteModel(
            name='MysqlBackupSourceInfo',
        ),
    ]
